pinger/src/linux.rs: use "ping -6" instead of "ping6"
`ping6` does not exist on my system (`iputils 20250605-1`)

`gping -6` fails otherwise.

```
$ gping -6 example.com
Error: Error spawning ping: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)
```

Note: Probably don't need to modify the BusyBox command.
However, `busybox ping` supports the same `-4/-6` flags:
```
$ busybox ping --help
...
-4,-6           Force IP or IPv6 name resolution
```